### PR TITLE
Jake dev

### PR DESCRIPTION
**Pull request by JakeAlbee**
I changed around some test files to isolate some functions and work better with others.

I added a __delitem__ to the ScopeLevelBean to facilitate deleting full variables from the ScopeLevelBean. 

Started to look at the bytes call but we may have a bug there that needs to be looked at.

### CODE REVIEW

**Comment by daviis** [comment]
Walker.visit_Bytes just prints out a string. What is it supposed to do?

**Comment by JakeAlbee** [comment]
I'm still working on that section, I thought I had removed it prior to making a pull request and I thought I put the working stuff in a new branch to request

**Comment by JakeAlbee** [comment]
So nothing as of now

**Comment by JakeAlbee** [comment]
Fixed it up so it was calling implicitly instead of explicitly. 

These are basically handled as lists so in the future we might need to make the scope for it like we are for lists, example being the contains method etc.

**Pull request merged**
