### PR TITLE
Improve function calling checks

### PR DESCRIPTION
**Pull request by daviis**
I made the ability to check functions for calling with kwargs, starargs and checks against calls where there are not enough parameters. 

Also included a new exception for when the FunDefWalker finds multiple return types for a function.

### CODE REVIEW

**Comment by daviis** [comment]
Fixes issues #83 #79

**Comment by JakeAlbee** [comment]
I'm getting some errors on testAll with control.py, it won't finish the testing due to an attribute error

**Comment by daviis** [comment]
Both of those things have been fixed. visit_for wasn't using VarBean.recursiveClone and visit_Subscript was wrapping VarBean.nextSubType in an outer VarBean.

Now it just raises an exception about not being able to super type.

**Comment by daviis** [comment]
Should be good to go now.

**Comment by JakeAlbee** [comment]
So I'm still getting errors when I run testAll, on control -- 

IncorrectMethodException
	On line: 32
	Can not find method: __contains__
	In class: list
	With args: int,

on MethodDef

```RefBeforeAssignException
	On line: 6
	Variable name: a is not in scope
	
	Because it was referenced before it was assigned.

**Pull request merged**
