### PR TITLE
Class self. things

### PR DESCRIPTION
**Pull request by daviis**
Not ready.

This has the rewrite to visit_attribute and visit_call we will need to talk about how we will go about differentiating between internal variables and classes.

### CODE REVIEW

**Comment by daviis** [comment]
#81

**Comment by daviis** [comment]
IT WORKS !!!! :) :) I still have to do unit testing but it is very close to being right.

**Comment by daviis** [comment]
Ready to be looked over and merged.

**Comment by JakeAlbee** [comment]
I'm getting an error on the following. I don't know if it's something to do with self-calls or not. But here it is

```File name:  ../Test/Correct/control.py
Tree Dump:  Module(body=[Assign(targets=[Name(id='x', ctx=Store())], value=Num(n=0)), While(test=Compare(left=Name(id='x', ctx=Load()), ops=[Lt()], comparators=[Num(n=10)]), body=[Expr(value=BinOp(left=Name(id='x', ctx=Load()), op=Add(), right=Num(n=1))), Break()], orelse=[]), While(test=Compare(left=Name(id='x', ctx=Load()), ops=[Lt()], comparators=[Num(n=10)]), body=[Expr(value=BinOp(left=Name(id='x', ctx=Load()), op=Add(), right=Num(n=2))), Continue()], orelse=[]), While(test=Compare(left=Name(id='x', ctx=Load()), ops=[Lt()], comparators=[Num(n=10)]), body=[AugAssign(target=Name(id='x', ctx=Store()), op=Add(), value=Num(n=1))], orelse=[]), Assign(targets=[Name(id='a', ctx=Store())], value=List(elts=[Num(n=1), Num(n=2), Num(n=3), Num(n=4)], ctx=Load())), For(target=Name(id='x', ctx=Store()), iter=Name(id='a', ctx=Load()), body=[Expr(value=BinOp(left=Name(id='x', ctx=Load()), op=Add(), right=Num(n=1)))], orelse=[]), Expr(value=Compare(left=Num(n=1), ops=[Is()], comparators=[Num(n=1)])), Expr(value=Compare(left=Num(n=1), ops=[IsNot()], comparators=[Num(n=1)])), Assert(test=NameConstant(value=False), msg=BinOp(left=Num(n=1), op=Add(), right=Num(n=2))), Assign(targets=[Name(id='b', ctx=Store())], value=IfExp(test=Num(n=2), body=Num(n=1), orelse=Num(n=3))), Expr(value=Compare(left=Num(n=1), ops=[In()], comparators=[List(elts=[Num(n=1), Num(n=2)], ctx=Load())])), Expr(value=Compare(left=Num(n=3), ops=[NotIn()], comparators=[List(elts=[Num(n=1), Num(n=2)], ctx=Load())])), Assign(targets=[Name(id='w', ctx=Store())], value=Str(s='a')), If(test=Compare(left=Name(id='w', ctx=Load()), ops=[In()], comparators=[Dict(keys=[Str(s='a'), Str(s='b')], values=[Num(n=1), Num(n=2)])]), body=[Pass()], orelse=[])])

 IncorrectMethodException
	On line: 32
	Can not find method: __contains__
	In class: list
	With args: int,

**Comment by JakeAlbee** [comment]
It is not, as it is in the current master branch. This all look sgood and works/passes all my tests. Merging in

**Comment by daviis** [comment]
That is the error it has always been getting. It has to do with lists
lookup taking an object type instead of the list's comp type. So once
inheritance is done we can look at that.

**Pull request merged**
