### PR TITLE
First changes post January

### PR DESCRIPTION
**Pull request by daviis**
The visits implemented are:
* Div
* FloorDiv
* Index
* Mod
* Not
* Pow
* Sub
* Assert
* IfExp
* Is
* ExceptHandler
* Raise
* Try
* Break
* Continue

Also have code for new tests:
* Test/Correct/Collections.py
* Test/Correct/Compare.py 
* Test/Correct/Ops.py (merged from addedTests)
* Test/Correct/control.py (merged from addedTests)
* Test/Correct/tryRaiseExcept.py (merged from addedTests)
* Test/Correct/SliceIndex.py

Removed tests:
* Test/Correct/Bin.py
* Test/Correct/BinOp.py
* Test/Correct/SingleMethodDef.py
* Test/Correct/UnOp.py
* Test/Correct/add.py

Altered test:
* Test/Incorrect/StrPlusInt.py so it doesn't have the print which isn't in the namespace yet.

In Bean.py I moved the function checking into the namespacebean then down further into the individual components. Along with that I moved exception creation into the beans (look at exceptions.py for changes there). Exceptions are also now made in ClassDefBean so when isIterable or a similar function is called it will either throw an exception or not do anything if it works.

In Exceptions.py I changed most creators from being strings to either VarBeans or ClassDefBeans or FunDefBeans. I also made lineNum an optional part of the creator because when Exceptions are spawned in the NameSpace or below they wont have access to the node that was their originator, so now there are exception handlers in the walker to catch possible exceptions and put the lineNum into them before reraiseing them.

In NameSpaceBean.py I set up the code so we can prime the environment with scope information.

In TestAST.py I made it possible to unit test all incorrect cases, also I started working on how we might print out exceptions to the user.

In Walker.py I implemented the new visits and refactored the exceptions/namespace checks.

### CODE REVIEW

**Comment by daviis** [comment]
Issue #57 is completed.
Issue #54 is started here.

**Comment by JakeAlbee** [comment]
I'll make comments as I check through since it's a pretty big pull request.

First off tests all look right and are working fine.

**Comment by JakeAlbee** [comment]
The NameSpace changes all look correct and test correctly for me.

The TestAST.py changes to the way we test all is a good idea and works. The exception handling looks right to me as well. I don't see any issues as of now with it

**Comment by JakeAlbee** [comment]
Exception handling makes sense and is a good change, works with testing

**Comment by JakeAlbee** [comment]
All of the bean changes make sense and work, they're good changes and leave us in a good spot to go forward with

**Comment by JakeAlbee** [comment]
Walker changes all make sense, everything looks good merging it in

**Pull request merged**
